keys:
  - &eva age1l4ryz3p32ylrgf98s46d2hgj0q8plcdnxa74h5gda0msmu06zuds6xeyjc
  - &stone age1swzurp0slgznhx7s8w9hjk3t6ncgguy8z7xumw8pcf5lrun8lycqct6yg5
  - &claude age1hwzgc327phsapeqf6q3jtc86pu3pk40pk36zejev0lplhfz5e5xqk7mmec
  - &twink age1hytys9s5sapstxh2ua7wncee6hlv8m6g6ldd9fqnjtz3kt9wsprqft2zus

creation_rules:
  - path_regex: '^secrets\.claude\.yaml$'
    key_groups:
      - age:
          - *eva
          - *claude
  - path_regex: '.+\.yaml$'
    key_groups:
      - age:
          - *eva
          - *stone
          - *twink
