#!/usr/bin/env sh

if [ -z "$HOME" ]; then
  echo "HOME unset!"
  exit 1
fi

function __find {
  find -not -path '.' -not -path './.git/*' -not -name link $@
}

find -type f -name '*.rs' -exec sh -c \
  'rustc -C opt-level=z -C panic=abort -C lto $0 -o ${0%.rs}' {} \;

for d in $(__find -type d); do
  echo "creating $HOME/$d"
  mkdir -p "$HOME/$d"
done

for d in $(__find -type f); do
  if [ "$(basename "$d")" = ".gitignore" ]; then
    continue
  fi
  echo "linking $d -> $HOME/$d"
  ln -sf "$PWD/$d" "$HOME/$d"
done

## TODO a better way to do this
rm -rf "$HOME/.config/VSCodium - Insiders" "$HOME/.config/Code - OSS"
ln -sf "$HOME/.config/VSCodium/" "$HOME/.config/VSCodium - Insiders"
ln -sf "$HOME/.config/VSCodium/" "$HOME/.config/Code - OSS"
