# The host-level half of the home-infra split.
#
# Nomad job definitions used to live in this repo, generated as JSON inside
# NixOS modules and self-registered over the Nomad API at activation
# (module/testbench-web.nix and module/ollama.nix still do this). They now live
# in ~/code/home-infra as plain .nomad.hcl and are pushed with `nomad job run`.
#
# What could not move is everything a job is not allowed to do for itself: a
# container cannot open a hole in the host firewall, and it cannot create a
# directory outside its own mounts with the right ownership before it first
# starts. Those two things are what this module is, and they are the reason the
# split is at this line rather than somewhere else.
#
# The split also stopped being optional once the cluster started moving to
# diskless netboot (EVA-298). A node whose entire filesystem is a read-only
# squashfs built from a lean module set cannot host-provision itself at all, and
# any job whose config arrives as a bind-mounted /nix/store path generated by a
# module that node does not import will simply fail to start. Jobs in home-infra
# carry their config in `template` stanzas for exactly that reason.
{ lib, ... }:
{
  # Ports the home-infra jobs bind on the LAN.
  #
  # Every one of these is unauthenticated and open to the whole home network,
  # which is the same trust assumption the cluster already runs on — but it is
  # an assumption, so each port says what it is rather than being a bare number
  # in a list.
  networking.firewall.allowedTCPPorts = [
    # infra/traefik.nomad.hcl — ingress (EVA-332). 80, moved from 8090 on
    # 2026-09-10 so *.gastrodon.io (EVA-281) resolves to the default HTTP port.
    80
    8090 # kept temporarily for anything with the old address cached.

    # Traefik dashboard/API — LAN-only, never funnelled (runs with
    # api.insecure, i.e. no auth).
    8091

    # infra/mysql.nomad.hcl. Cross-node reachability here is incidental
    # (podman's port publishing), not declared by this file.
    3306

    # infra/rabbitmq (amqp + management UI), for the iFunny ETL jobs.
    5672
    15672

    # infra/samba.nomad.hcl — PS2 game share (EVA-373). SMB1/NT1, forced by
    # the PS2 client — LAN-only, must never be reachable outside it. See wiki:
    # "PS2 SMB1 samba share — accepted risk" (EVA-373/376).
    445

    # module/ollama.nix — model server.
    11434

    # Home Assistant + testbench viewer. BACKEND ports reached by traefik from
    # whichever node it lands on, not dialed by a human directly.
    8123
    8087

    # infra/blocky.nomad.hcl — internal DNS for *.gastrodon.io (EVA-281). TCP
    # as well as UDP: DNS falls back to TCP for oversized responses.
    53

    # infra/gitea.nomad.hcl — decomp artifact/results host (EVA-369). Same
    # backend-port shape as home-assistant/testbench above.
    3000

    # infra/vault.nomad.hcl (EVA-303). 8200 is the API; 8201 is Raft
    # replication, unused at count = 1 but reserved.
    8200
    8201
  ];

  # Nomad's dynamic port range (client.min_dynamic_port/max_dynamic_port,
  # left at default). Closes EVA-324's second bug: a job using a
  # Nomad-assigned dynamic port has no way to get a pre-declared firewall
  # rule. See wiki: "Cluster firewall & port map" (EVA-324).
  networking.firewall.allowedTCPPortRanges = [
    {
      from = 20000;
      to = 32000;
    }
  ];

  # blocky — DNS is UDP-first; without this the resolver is invisible to
  # every client despite looking healthy to Nomad.
  networking.firewall.allowedUDPPorts = [ 53 ];

  # Same dynamic-port reasoning as the TCP range above, for UDP-based jobs.
  networking.firewall.allowedUDPPortRanges = [
    {
      from = 20000;
      to = 32000;
    }
  ];

  # durable-storage ownership: see module/nomad-storage.nix

  # Trust for infra/registry.nomad.hcl — LAN OCI registry at .17:20500, plain
  # HTTP. See wiki: "Cluster firewall & port map".
  virtualisation.containers.registries.insecure = [ "192.168.0.17:20500" ];
}
