# The host-level half of the home-infra split.
#
# Nomad job definitions used to live in this repo, generated as JSON inside
# NixOS modules and self-registered over the Nomad API at activation
# (module/testbench-web.nix and module/ollama.nix still do this). They now live
# in ~/code/home-infra as plain .nomad.hcl and are pushed with `nomad job run`.
#
# What could not move is everything a job is not allowed to do for itself: a
# container cannot open a hole in the host firewall, and it cannot create a
# directory outside its own mounts with the right ownership before it first
# starts. Those two things are what this module is, and they are the reason the
# split is at this line rather than somewhere else.
#
# The split also stopped being optional once the cluster started moving to
# diskless netboot (EVA-298). A node whose entire filesystem is a read-only
# squashfs built from a lean module set cannot host-provision itself at all, and
# any job whose config arrives as a bind-mounted /nix/store path generated by a
# module that node does not import will simply fail to start. Jobs in home-infra
# carry their config in `template` stanzas for exactly that reason.
{ lib, ... }:
{
  # Ports the home-infra jobs bind on the LAN.
  #
  # Every one of these is unauthenticated and open to the whole home network,
  # which is the same trust assumption the cluster already runs on — but it is
  # an assumption, so each port says what it is rather than being a bare number
  # in a list.
  networking.firewall.allowedTCPPorts = [
    # infra/traefik.nomad.hcl — the single ingress point (EVA-332). Without
    # this rule Traefik listens correctly and answers nothing from anywhere but
    # its own host, which is exactly how it first came up.
    #
    # 80, moved from 8090 on 2026-09-10. DNS carries an address and not a port,
    # so once blocky answers `<service>.gastrodon.io -> <traefik>` (EVA-281) a
    # client goes to :80. On 8090 every internal name resolved and then
    # connected to nothing.
    80

    # 8090 kept alongside it, deliberately and temporarily. Anything with the
    # old address cached or written down keeps working through the transition;
    # remove it once nothing has used it for a while. Costs one firewall rule.
    8090

    # Traefik's dashboard/API. LAN-only and deliberately never funnelled — the
    # dashboard runs with `api.insecure`, i.e. no authentication, so the
    # firewall is the only thing in front of it.
    8091

    # infra/mysql.nomad.hcl. Reachable cross-node today without an explicit
    # rule, which is a property of how the podman driver publishes ports rather
    # than of anything declared here; stating it makes the reachability
    # intentional instead of incidental, and keeps it working if that changes.
    3306

    # infra/rabbitmq (amqp + management UI), if/when the iFunny ETL jobs are
    # brought up — see ifunny-etl/PORTED.md. Harmless while nothing listens.
    5672
    15672

    # module/ollama.nix — the model server. Without this the API answers only
    # on its own host, which is how it looked "running" while pibot's
    # http://<node>:11434/v1 endpoint timed out.
    11434

    # Home Assistant and the testbench viewer. These are BACKEND ports, reached
    # by traefik from whichever node it landed on — not ports a human dials.
    #
    # Their absence was invisible until routing existed. With the jobs pinned by
    # IP and traefik on the same box, loopback made it work; once the jobs moved
    # to volume-based placement and traefik ended up on a different node, both
    # routes timed out with HTTP 000 while Nomad reported every task `running`
    # and every health check green. Measured 2026-09-10: from .58,
    # `.17:11434` reachable, `.17:8123` and `.17:8087` BLOCKED.
    #
    # The general rule this is an instance of: any port a service listens on
    # must be open cluster-wide the moment that service stops being pinned to
    # one box, because "the client" is now traefik on an arbitrary node.
    8123
    8087

    # infra/blocky.nomad.hcl — internal DNS for *.gastrodon.io (EVA-281).
    # TCP as well as UDP: DNS falls back to TCP for responses that do not fit
    # in a UDP datagram, and a resolver that answers small queries while timing
    # out on large ones is a uniquely horrible thing to debug.
    53

    # infra/gitea.nomad.hcl — the decomp artifact/results host (EVA-369,
    # docs/artifact-hosting-plan.md in merc-reveng). Same shape as the
    # home-assistant/testbench entries above and for the same reason: this is
    # a BACKEND port, reached by traefik from whichever node the `gitea` host
    # volume pins it to (.17), not a port a human dials directly. Without this
    # rule the job comes up healthy and answers only on its own host, and
    # traefik on .58 times out reaching it the same way .17:8123 did before
    # this list existed.
    3000

    # infra/vault.nomad.hcl (EVA-303). 8200 is the API — every job's Vault
    # template hits this. 8201 is Raft's own replication port; unused at
    # count = 1, but the jobspec's `network` block reserves it and a future
    # multi-voter Vault would need it open with no other change here.
    8200
    8201
  ];

  # blocky again, and this is the half that is easy to forget. DNS is UDP
  # first — without this the resolver binds correctly, answers on its own
  # host, and is invisible to every client on the LAN and the tailnet.
  #
  # That is the same shape as the traefik/ollama/home-assistant firewall gaps
  # found earlier today, and the rule is worth stating once: a service only
  # reachable from its own host looks completely healthy to Nomad, because the
  # health check runs there too.
  networking.firewall.allowedUDPPorts = [ 53 ];

  # Bind-mount targets for the disk-backed jobs, created before any job starts.
  #
  # Ownership is not cosmetic: rootful podman passes container uids straight
  # through, so the mysql image's uid 999 has to own /data/mysql on the host or
  # the server exits on its first write. Creating these lazily from inside the
  # container is what podman does when the path is missing, and it creates them
  # root-owned — which is how a first deploy fails on permissions.
  #
  # /data/mysql is the fix for EVA-325, where the datadir was
  # `--datadir=/dev/shm/mysql-data` and every task restart silently destroyed
  # the whole database. It happened twice.
  # NO tmpfiles rules for /data here, deliberately, and this is a correction
  # rather than an omission.
  #
  # This module used to declare `d /data 0755` and `d /data/mysql 0700 999 999`.
  # systemd-tmpfiles runs early and unconditionally, so on a node whose data
  # disk failed to mount those rules create the directories on the ROOT
  # filesystem -- tmpfs, on a netbooted node -- and the later mount hides them.
  # Nomad then places MySQL onto a directory in RAM that looks entirely
  # correct and evaporates at the next reboot. That is EVA-325's shape again.
  #
  # module/nomad-storage.nix owns /data now and creates nothing: it proves the
  # backing store is durable first, and only then reads what is already there.

  # NOT SET HERE, ON PURPOSE — the EVA-192 hostname fix.
  #
  # These boxes disagree about their own names. `derive-hostname` runs at boot,
  # correctly sets ip-192-168-0-58, and is then overruled: hosts/shared.nix
  # enables NetworkManager, whose default hostname-mode resolves the primary
  # address back to a name, and networking.extraHosts (from module/hosts.nix)
  # maps 192.168.0.58 → server1 in /etc/hosts. So NetworkManager restores
  # `server1` seconds after the unit sets the derived name. 192.168.0.5 has no
  # entry in module/hosts.nix and is the one box that keeps its derived name —
  # the natural experiment that confirms the mechanism.
  #
  # The fix is one line, `networking.networkmanager.settings.main.hostname-mode
  # = "none"`, but applying it renames two boxes, and the Tailscale MagicDNS
  # name follows the hostname. 192.168.0.58's name is the public Funnel URL
  # registered with Linear (EVA-273), so the rename is a webhook outage until
  # that URL is re-registered. That makes it a deliberate change with a
  # follow-up step, not a drive-by, and it should land together with the
  # Traefik ingress switch rather than before it.
}
