# schpet/linear-cli — Linear issue tracker from the command line, packaged from the
# upstream cargo-dist release tarball (a Deno single-file executable, so the binary
# carries an appended payload: stripping truncates it, hence dontStrip).
#
# Auth resolves as --api-key > LINEAR_API_KEY > .linear.toml > OS keyring. We take the
# env var and feed it from sops (see module/linear.nix), which keeps `linear auth login`
# and its libsecret keyring entirely out of the picture — no interactive runtime state.
{ pkgs, lib, ... }:
let
  version = "2.5.0";

  linear-cli = pkgs.stdenv.mkDerivation {
    pname = "linear-cli";
    inherit version;

    src = pkgs.fetchurl {
      url = "https://github.com/schpet/linear-cli/releases/download/v${version}/linear-x86_64-unknown-linux-gnu.tar.xz";
      hash = "sha256-Yqzp+2NsMcXpf4SQ6GGC8BK5pLOiwNO/jI3ekGA5w+o=";
    };

    nativeBuildInputs = [
      pkgs.autoPatchelfHook
      pkgs.installShellFiles
    ];
    buildInputs = [ pkgs.stdenv.cc.cc.lib ];

    dontStrip = true;
    dontBuild = true;

    installPhase = ''
      runHook preInstall
      install -Dm755 linear $out/bin/linear
      runHook postInstall
    '';

    # Completions are generated by the binary itself, so they have to come after
    # autoPatchelf has made it runnable.
    postFixup = ''
      installShellCompletion --cmd linear \
        --bash <($out/bin/linear completions bash) \
        --zsh <($out/bin/linear completions zsh) \
        --fish <($out/bin/linear completions fish)
    '';

    meta = with lib; {
      description = "Linear without leaving the command line: list, start, and create PRs for Linear issues";
      homepage = "https://github.com/schpet/linear-cli";
      license = licenses.isc;
      platforms = [ "x86_64-linux" ];
      mainProgram = "linear";
    };
  };
in
{
  home.packages = [ linear-cli ];

  # Read at shell start rather than baked in: the value lives only in the sops runtime
  # secret. Guarded so a shell on a host without the secret still starts clean.
  programs.zsh.initContent = lib.mkOrder 550 ''
    [ -r /run/secrets/linear/api_key ] && export LINEAR_API_KEY="$(< /run/secrets/linear/api_key)"
  '';
}
