#!/bin/sh

echo 'exit' | sudo -s || exit

rm -rf "$HOME/.dotfiles" \
  && ln -s $(pwd) "$HOME/.dotfiles" 2>/dev/null || :

mkdir -p $HOME/.{config,font,oh-my-zsh/custom}
for it in \
  "tokens" "zshrc" "wall.png" "gitignore" \
  "xinitrc" "xprofile" "Xresources" \
  "font/gomme" "oh-my-zsh/custom/themes" \
  config/{i3,polybar,picom} \
  ; do
  rm -rf "$HOME/.$it" && ln -s $HOME/{.dotfiles/,}.$it
done

sudo rm -rf "/usr/share/fonts/dotfile" \
  && sudo ln -s "$HOME/.font" "/usr/share/fonts/dotfile"
