name: Build NixOS Configuration

on:
  workflow_dispatch:

jobs:
  build:
    name: Build NixOS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Build NixOS configuration
        run: |
          echo "Building NixOS configuration..."
          nix build .#nixosConfigurations.twink.config.system.build.toplevel --impure --show-trace
